apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: {{ name }}
        image: simonmok/jhub-gofer
        command: [
          "python", "worker.py", 
          "--api-server", "{{ api_addr }}"]
      restartPolicy: Never
