apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 3
  template:
    spec:
      containers:
      - name: {{ name }}
        image: simonmok/jhub-gofer:latest
        command: [
          "python", "worker.py", 
          "--api-url", "{{ api_addr }}"]
      restartPolicy: Never
